services:
  suno:
    working_dir: /home/app/suno
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:3000"
    expose:
      - "3000"
    restart: on-failure
    networks:
      - proxy-net
    env_file:
      - .env

networks:
  proxy-net:
    driver: bridge
